site_name: PlayStation Specifications - psx-spx
site_url: https://psx-spx.consoledev.net/
repo_url: https://github.com/psx-spx/psx-spx.github.io/
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: material/sony-playstation
  features:
    - navigation.path

hooks:
  - tools/bitfields/hook.py

plugins:
  - search
  - with-pdf:
      output_path: psx-spx.pdf

extra_css:
  - css/extra.css

markdown_extensions:
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - 'index.md'
  - 'aboutcredits.md'
  - PlayStation 1:
      - 'ps1/kernelbios.md'
      - 'ps1/hardwarenumbers.md'
      - 'ps1/memorymap.md'
      - 'ps1/iomap.md'
      - 'ps1/pinouts.md'
      - CPU:
          - GTE:
              - 'ps1/cpu/gte/geometrytransformationenginegte.md'
              - 'ps1/cpu/gte/gtepipelinetimings.md'
          - MDEC:
              - 'ps1/cpu/mdec/macroblockdecodermdec.md'
          - 'ps1/cpu/memorycontrol.md'
          - 'ps1/cpu/partialwordwrites.md'
          - 'ps1/cpu/unpredictablethings.md'
          - 'ps1/cpu/cpuspecifications.md'
          - 'ps1/cpu/interrupts.md'
          - 'ps1/cpu/dmachannels.md'
          - 'ps1/cpu/timers.md'
      - GPU:
          - 'ps1/gpu/graphicsprocessingunitgpu.md'
      - SPU:
          - 'ps1/spu/soundprocessingunitspu.md'
      - CD-ROM:
          - 'ps1/cdr/cdromdrive.md'
          - 'ps1/cdr/cdromformat.md'
          - 'ps1/cdr/cdromfileformats.md'
          - 'ps1/cdr/cdrominternalinfoonpsxcdromcontroller.md'
          - 'ps1/cdr/cdromvideocdsvcd.md'
      - SIO:
          - 'ps1/sio/serialinterfacessio.md'
          - 'ps1/sio/controllersandmemorycards.md'
          - 'ps1/sio/pocketstation.md'
      - PIO:
          - 'ps1/pio/expansionportpio.md'
          - 'ps1/pio/cheatdevices.md'
  - Sony DTL-H2xxx:
      - 'dtl/psxdevboardchipsets.md'
      - 'dtl/psxdevboardprotocol.md'
  - Arcade Boards:
      - 'arcade/arcadecabinets.md'
      - Konami:
          - 'arcade/konami/konami-gq.md'
          - 'arcade/konami/konami-gv999.md'
          - 'arcade/konami/573/konamisystem573.md'